### ISSUE TITLE
Improve Primary Button Legibility

### ISSUE THREAD

**Issue by seandebutts** [dotnet/core-docs#192]
In the TOC pages, the buttons for "Improve this Doc" and "View Source" are difficult to read because of purple text against blue background. 

Examples: 
http://dotnet.github.io/api/index.html, and the pages below it (also http://dotnet.github.io/docs/).

/cc @blackdwarf @chenkennt @pengbian

**Comment by blackdwarf** [comment]
@seandebutts this is planned as part of the overall CSS changes this or next week, but thanks for putting up the issue for tracking.

**Comment by blackdwarf** [comment]
This has been fixed. so closing.

**Comment by mairaw** [comment]
Looks much better now :smile:

**Comment by svick** [comment]
Is this change live? I still see the same issue on e.g. http://dotnet.github.io/api/System.html.

**Comment by seandebutts** [comment]
Agreed, the buttons on those two pages look nice and clean: http://dotnet.github.io/api/index.html and http://dotnet.github.io/api/index.html

@svick I also am still seeing the old "Improve this Doc" button on the API Reference pages such as: http://dotnet.github.io/api/System.html

@blackdwarf Should we reopen this?

cc: @mairaw
